package com.project.demo.model;

public enum SphereOfInterest {
    MUSIC, SPORT, SCIENCE, INTERPERSONAL_RELATIONSHIP, HISTORY, LEARNING,
    SHOW_BUSINESS, TECHNOLOGY, CREATIVITY, FOOD, WORLD_LITERATURE, CELEBRITY,
    ADVENTURE, TRUE_EVENTS, FICTION, HISTORY_OF_LITERATURE, FUN
}

