package com.project.demo.model;

public enum SphereOfInterest {
    MUSIC, SPORT, SCIENCE, INTERPERSONAL_RELATIONSHIP, LANGUAGES, HOSTORY, LEARNING,
    SHOW_BUSINESS, TECHNOLOGY, MECHANICS, CREATIVITY, LOVE, FOOD, PARENTING
}
