package rules;
dialect  "mvel"

import com.project.demo.model.User;
import com.project.demo.model.Age;

rule "Child User"
    salience 10
    no-loop
    when
        u : User(age < 13, intAge: age)
    then
        modify(u){setAgeGroup(Age.CHILD)};
end

rule "Young User"
    salience 10
    no-loop
    when
        u : User(age > 12, age < 22, intAge: age)
    then
        modify(u){setAgeGroup(Age.YOUNG)};
end


rule "Adult User"
    salience 10
    no-loop
    when
        u : User(age > 21, age < 59, intAge: age)
    then
        modify(u){setAgeGroup(Age.ADULT)};
end


rule "Elder User"
    salience 10
    no-loop
    when
        u : User(age > 58, intAge: age)
    then
        modify(u){setAgeGroup(Age.ELDER)};
end

